
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: alex
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: library_app_development

test:
  <<: *default
  database: library_app_test

production:
  <<: *default
  database: library_app_production
  username: library_app
  password: <%= ENV['LIBRARY_APP_DATABASE_PASSWORD'] %>
